#ifndef NASTEROIDS_CONSTANTS_H
#define NASTEROIDS_CONSTANTS_H

#define GRAVITY 6.674e-5
#define TIME_INTERVAL 0.1
#define MINIMUM_DISTANCE 2.0
#define SPACE_WIDTH 200
#define SPACE_HEIGHT 200
#define RAY_WIDTH 4
#define MASS 1000
#define SD_MASS 50
#define PARAMETERS_REQUIRED 5
#define MAXIMUM_FORCE 200

#endif //NASTEROIDS_CONSTANTS_H
